name: Coding Standards

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-20.04
    env:
      TTY: -T

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Start app container
        run: task docker:up:test -- dbsaver:9000

      - name: Run PHP CS Fixer
        run: task docker:app:phpcs:ci