name: Security Check

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for vulnerabilities
        uses: symfonycorp/security-checker-action@v3
        with:
          disable-exit-code: 1
        id: security-check

      - name: Display vulnerabilities as JSON
        run: echo ${{ steps.security-check.outputs.vulns }}