name: Security Check

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display vulnerabilities as JSON
        uses: symfonycorp/security-checker-action@v3