name: Static Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    env:
      TTY: -T

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Start app container
        run: task docker:up:test -- dbsaver:9000

      - name: Run PHPStan
        run: task docker:app:phpstan